stages:
  - base_images
  - sdk_images
  - ndk_images
create_base_images:
    stage: base_images
    image: norbnorb/vcs
    only:
      - master
    before_script:
      - |
        echo "Preparing SSH"
        mkdir -p ~/.ssh
        echo "Host gitlab.norbert-ruehl.de" > ~/.ssh/config
        echo "User git" >> ~/.ssh/config
        echo "IdentityFile ${SSH_KEY}" >> ~/.ssh/config
        ssh-keyscan -t rsa gitlab.norbert-ruehl.de >> ~/.ssh/known_hosts
        chmod 600 ${SSH_KEY}
    script:
      - git remote set-url origin git@gitlab.norbert-ruehl.de:nruehl/docker-android
      - git checkout -B base
      - git checkout ${CI_COMMIT_SHA} Dockerfile
      - git add Dockerfile
      - git config user.email "ci-runner-docker-android@norbert-ruehl.de"
      - git config user.name "ci runner"
      - git commit -am "[CI] Updated Dockerfile From Master" || true
      - git push -u origin base
    after_script:
      - |
        echo "Cleaning Up"
        rm -rf ~/.ssh

