stages:
  - base_images
  - sdk_images
  - ndk_images
create_base_images:
    stage: base_images
    image: norbnorb/vcs
    only:
      - master
    script:
      - git checkout -B base
      - git checkout ${CI_COMMIT_SHA} Dockerfile
      - git add Dockerfile
      - git config user.email "ci-runner-docker-android@norbert-ruehl.de"
      - git config user.name "ci runner"
      - git commit -am "[CI] Updated Dockerfile From Master"
      - git push -u origin base 
